services:
  bot:
#    image: python:3.11-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pump_up_your_ass
    user: root
    ports:
      - 8010:8010
    volumes:
      - .:/pump_up_your_ass
    working_dir: /pump_up_your_ass
    environment:
      TOKEN: token
      DB_HOST: postgres_puya
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_PORT: 5432

networks:
  default:
    name: pump_up_your_ass_network
    external: true