version: "1.0"
services:
  bot:
    image: melnichenkodmitry/pump_up_your_ass
    container_name: pump_up_your_ass
    ports:
      - 8010:8010
    volumes:
      - .:/home/pump_up_your_ass
networks:
  default:
    name: pump_up_your_ass_network
    external: true